# Generated by Django 4.1.7 on 2023-02-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rollno', models.TextField(max_length=500)),
                ('Intime', models.TimeField()),
                ('Outtime', models.TimeField()),
                ('nodeno', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Newapp',
        ),
    ]
